/**
 * each spaceship is controlled by an AI. This class keeps all the spaceship related data and updates the space ship based on the AI's commands
 */
package AiCompetition.com;

import AiCompetition.com.commands.ShootCommand;
import AiCompetition.com.commands.ThrustCommand;

import java.util.ArrayList;

public class Spaceship
{
    private SpaceshipStructure structure;
    private float xPos;
    private float yPos;
    private float xVel;
    private float yVel;
    private float direction;
    private int energy; //the amount of energy the spaceship currently have

    /**
     * called before the match begins
     *
     * @param structure - the structure of the spaceship as created by the AI
     */
    public void init(SpaceshipStructure structure)
    {
        this.setStructure(structure);
        //TODO
    }

    /**
     *
     * @param shootCommands - the commands that were generated by the AI
     */
    public void executeShootCommands(ArrayList<ShootCommand> shootCommands)
    {
        // TODO - shoot bullets based on the command
        // IMPORTANT - check if there is enough energy
    }

    /**
     *
     * @param thrustCommands - the commands that were generated by the AI
     */
    public void executeThrustCommands(ArrayList<ThrustCommand> thrustCommands)
    {
        // TODO - activate thrusters
        // IMPORTANT - check if there is enough energy
    }

    /**
     * updates the spaceship
     *
     * @param deltaTime
     */
    public void update(float deltaTime)
    {
        //TODO
    }

    public int getEnergy()
    {
        return energy;
    }

    public void setEnergy(int energy)
    {
        this.energy = energy;
    }

    public SpaceshipStructure getStructure()
    {
        return structure;
    }

    public void setStructure(SpaceshipStructure structure)
    {
        this.structure = structure;
    }

    public float getxPos()
    {
        return xPos;
    }

    public void setxPos(float xPos)
    {
        this.xPos = xPos;
    }

    public float getyPos()
    {
        return yPos;
    }

    public void setyPos(float yPos)
    {
        this.yPos = yPos;
    }

    public float getxVel()
    {
        return xVel;
    }

    public void setxVel(float xVel)
    {
        this.xVel = xVel;
    }

    public float getyVel()
    {
        return yVel;
    }

    public void setyVel(float yVel)
    {
        this.yVel = yVel;
    }

    public float getDirection()
    {
        return direction;
    }

    public void setDirection(float direction)
    {
        this.direction = direction;
    }
}
